portfolio_monitor:
  portfolio_path: "config/portfolios"
  aggregate_cache_path: "config/aggregate_cache.db"
  auth_key: "${private.portfolio_monitor.auth_key}"

  dashboard:
    username: "${private.portfolio_monitor.dashboard.username}"
    password: "${private.portfolio_monitor.dashboard.password}"

  # Define the common set of detectors and give it an anchor
  all_detectors:
    average_true_range_move: {}
    SMA_deviation: {}
    percent_change_previous_close: {}
    percent_change: {}
    volume_spike: {}
    zscore_return: {}
    zscore_volume: {}

  monitors:
    default:

polygon:
  api_key: "${private.polygon.api_key}"

openclaw:
  auth_key: "${private.openclaw.auth_key}"
  session_key: "portfolio_alerts"
